export const nodes=[
    { id: 1, label: "Manual Scan",group:1},
    { id: 2, label: "Antivirus",group:2},
    { id: 3, label: "Firewall Detection",group:3},
    { id: 4, label: "Low"},
    { id: 5, label: "Medium"},
    { id: 6, label: "High",},
    { id: 7,group:2, size:16,title: "word.pages", File_Type: "zip", label: "Trojan", Malware_Severity: "Low", Detection_Method: "Antivirus", Affected_Process: "wear", Affected_System: "admit", User_Permissions: "User", Last_Modified_By: "Anthony Atkins" },
{ id: 8,group:1,size:18, title: "guy.json", File_Type: "exe", label: "Virus", Malware_Severity: "High", Detection_Method: "Manual Scan", Affected_Process: "money", Affected_System: "avoid", User_Permissions: "Admin", Last_Modified_By: "Shannon Crawford" },
{ id: 9,group:3,size:12,title: "room.css", File_Type: "pdf", label: "Virus", Malware_Severity: "High", Detection_Method: "Firewall Detection", Affected_Process: "opportunity", Affected_System: "with", User_Permissions: "Admin", Last_Modified_By: "Norman Powers" },
{ id: 10,group:2, size:16,title: "visit.ods", File_Type: "pdf", label: "Ransomware", Malware_Severity: "High", Detection_Method: "Antivirus", Affected_Process: "act", Affected_System: "drive", User_Permissions: "Admin", Last_Modified_By: "Pamela Howard" },
{ id: 11,group:1,size:18, title: "star.odt", File_Type: "zip", label: "Virus", Malware_Severity: "Medium", Detection_Method: "Manual Scan", Affected_Process: "social", Affected_System: "site", User_Permissions: "User", Last_Modified_By: "Eric Johnson" },
{ id: 12,group:1,size:18, title: "tend.mp3", File_Type: "exe", label: "Trojan", Malware_Severity: "Medium", Detection_Method: "Manual Scan", Affected_Process: "conference", Affected_System: "way", User_Permissions: "User", Last_Modified_By: "Jessica Murray" },
{ id: 13,group:3,size:12,title: "energy.tiff", File_Type: "pdf", label: "Ransomware", Malware_Severity: "Low", Detection_Method: "Firewall Detection", Affected_Process: "though", Affected_System: "car", User_Permissions: "Admin", Last_Modified_By: "Tammy Miller" },
{ id: 14,group:3,size:12,title: "edge.doc", File_Type: "exe", label: "Virus", Malware_Severity: "High", Detection_Method: "Firewall Detection", Affected_Process: "rest", Affected_System: "house", User_Permissions: "Admin", Last_Modified_By: "Crystal White" },
{ id: 15,group:1,size:18, title: "pretty.flac", File_Type: "zip", label: "Worm", Malware_Severity: "Medium", Detection_Method: "Manual Scan", Affected_Process: "scientist", Affected_System: "author", User_Permissions: "Admin", Last_Modified_By: "James Scott" },
{ id: 16,group:2, size:16,title: "too.jpg", File_Type: "pdf", label: "Worm", Malware_Severity: "Low", Detection_Method: "Antivirus", Affected_Process: "interest", Affected_System: "it", User_Permissions: "Admin", Last_Modified_By: "Lori Guzman" },
{ id: 17,group:2, size:16,title: "beyond.webm", File_Type: "pdf", label: "Worm", Malware_Severity: "High", Detection_Method: "Antivirus", Affected_Process: "relate", Affected_System: "show", User_Permissions: "Admin", Last_Modified_By: "Tina Nelson" },
{ id: 18,group:1,size:18, title: "administration.tiff", File_Type: "pdf", label: "Worm", Malware_Severity: "Medium", Detection_Method: "Manual Scan", Affected_Process: "set", Affected_System: "behind", User_Permissions: "Admin", Last_Modified_By: "Matthew Alexander" },
{ id: 19,group:1,size:18, title: "health.xlsx", File_Type: "zip", label: "Trojan", Malware_Severity: "Low", Detection_Method: "Manual Scan", Affected_Process: "stock", Affected_System: "professional", User_Permissions: "Admin", Last_Modified_By: "Sarah George" },
{ id: 20,group:1,size:18, title: "quite.gif", File_Type: "doc", label: "Virus", Malware_Severity: "Medium", Detection_Method: "Manual Scan", Affected_Process: "accept", Affected_System: "trade", User_Permissions: "Admin", Last_Modified_By: "Tammy Roberts" },
{ id: 21,group:3,size:12,title: "ground.js", File_Type: "pdf", label: "Virus", Malware_Severity: "High", Detection_Method: "Firewall Detection", Affected_Process: "lay", Affected_System: "begin", User_Permissions: "Admin", Last_Modified_By: "Lauren Hernandez" },
{ id: 22,group:1,size:18, title: "woman.jpg", File_Type: "zip", label: "Ransomware", Malware_Severity: "High", Detection_Method: "Manual Scan", Affected_Process: "control", Affected_System: "plan", User_Permissions: "Admin", Last_Modified_By: "Karen Pineda" },
{ id: 23,group:3,size:12,title: "American.js", File_Type: "doc", label: "Worm", Malware_Severity: "High", Detection_Method: "Firewall Detection", Affected_Process: "clearly", Affected_System: "smile", User_Permissions: "User", Last_Modified_By: "Marcus Jimenez" },
{ id: 24,group:2, size:16,title: "similar.xlsx", File_Type: "pdf", label: "Worm", Malware_Severity: "Low", Detection_Method: "Antivirus", Affected_Process: "first", Affected_System: "letter", User_Permissions: "Admin", Last_Modified_By: "Jeremy Gamble" },
{ id: 25,group:2, size:16,title: "though.flac", File_Type: "zip", label: "Ransomware", Malware_Severity: "High", Detection_Method: "Antivirus", Affected_Process: "third", Affected_System: "light", User_Permissions: "Admin", Last_Modified_By: "Sean Rosario" },
{ id: 26,group:3,size:12,title: "shoulder.css", File_Type: "zip", label: "Worm", Malware_Severity: "Medium", Detection_Method: "Firewall Detection", Affected_Process: "commercial", Affected_System: "assume", User_Permissions: "User", Last_Modified_By: "Robin Sanders" },
{ id: 27,group:3,size:12,title: "piece.webm", File_Type: "pdf", label: "Worm", Malware_Severity: "Low", Detection_Method: "Firewall Detection", Affected_Process: "film", Affected_System: "beat", User_Permissions: "User", Last_Modified_By: "Eric Ferrell" },
{ id: 28,group:3,size:12,title: "commercial.mov", File_Type: "exe", label: "Worm", Malware_Severity: "High", Detection_Method: "Firewall Detection", Affected_Process: "effort", Affected_System: "level", User_Permissions: "User", Last_Modified_By: "Alexander Hudson" },
{ id: 29,group:3,size:12,title: "see.jpg", File_Type: "doc", label: "Ransomware", Malware_Severity: "High", Detection_Method: "Firewall Detection", Affected_Process: "social", Affected_System: "agreement", User_Permissions: "Admin", Last_Modified_By: "Lisa Wolfe" },
{ id: 30,group:2, size:16,title: "eight.js", File_Type: "pdf", label: "Trojan", Malware_Severity: "High", Detection_Method: "Antivirus", Affected_Process: "north", Affected_System: "figure", User_Permissions: "User", Last_Modified_By: "Sandra Johnson" },
{ id: 31,group:1,size:18, title: "goal.avi", File_Type: "pdf", label: "Trojan", Malware_Severity: "Low", Detection_Method: "Manual Scan", Affected_Process: "laugh", Affected_System: "beautiful", User_Permissions: "User", Last_Modified_By: "Mrs. Jennifer Rangel PhD" },
{ id: 32,group:3,size:12,title: "individual.flac", File_Type: "pdf", label: "Worm", Malware_Severity: "High", Detection_Method: "Firewall Detection", Affected_Process: "play", Affected_System: "station", User_Permissions: "User", Last_Modified_By: "Colleen Garcia" },
{ id: 33,group:2, size:16,title: "want.mov", File_Type: "doc", label: "Virus", Malware_Severity: "Low", Detection_Method: "Antivirus", Affected_Process: "some", Affected_System: "professional", User_Permissions: "User", Last_Modified_By: "Jeffrey Williams" },
{ id: 34,group:3,size:12,title: "fight.pdf", File_Type: "doc", label: "Trojan", Malware_Severity: "Medium", Detection_Method: "Firewall Detection", Affected_Process: "create", Affected_System: "customer", User_Permissions: "Admin", Last_Modified_By: "David Hill" },
{ id: 35,group:3,size:12,title: "day.pdf", File_Type: "zip", label: "Virus", Malware_Severity: "Low", Detection_Method: "Firewall Detection", Affected_Process: "skin", Affected_System: "situation", User_Permissions: "Admin", Last_Modified_By: "Matthew Kemp" },
{ id: 36,group:2, size:16,title: "agency.png", File_Type: "zip", label: "Worm", Malware_Severity: "Medium", Detection_Method: "Antivirus", Affected_Process: "tend", Affected_System: "government", User_Permissions: "User", Last_Modified_By: "Justin Smith" },
{ id: 37,group:2, size:16,title: "friend.flac", File_Type: "zip", label: "Ransomware", Malware_Severity: "High", Detection_Method: "Antivirus", Affected_Process: "record", Affected_System: "team", User_Permissions: "Admin", Last_Modified_By: "Kara Reilly" },
{ id: 38,group:1,size:18, title: "pull.bmp", File_Type: "pdf", label: "Virus", Malware_Severity: "Low", Detection_Method: "Manual Scan", Affected_Process: "career", Affected_System: "hair", User_Permissions: "Admin", Last_Modified_By: "Marcus Berry" },
{ id: 39,group:2, size:16,title: "ok.docx", File_Type: "exe", label: "Worm", Malware_Severity: "Medium", Detection_Method: "Antivirus", Affected_Process: "hear", Affected_System: "watch", User_Permissions: "Admin", Last_Modified_By: "Mason Miller" },
{ id: 40,group:3,size:12,title: "consider.ods", File_Type: "exe", label: "Worm", Malware_Severity: "Medium", Detection_Method: "Firewall Detection", Affected_Process: "out", Affected_System: "ever", User_Permissions: "Admin", Last_Modified_By: "Wesley Mcdonald" },
{ id: 41,group:3,size:12,title: "yet.xlsx", File_Type: "exe", label: "Trojan", Malware_Severity: "Low", Detection_Method: "Firewall Detection", Affected_Process: "identify", Affected_System: "political", User_Permissions: "User", Last_Modified_By: "Adrian Weaver" },
{ id: 42,group:3,size:12,title: "activity.csv", File_Type: "exe", label: "Virus", Malware_Severity: "High", Detection_Method: "Firewall Detection", Affected_Process: "main", Affected_System: "range", User_Permissions: "Admin", Last_Modified_By: "Phillip Mccarthy" },
{ id: 43,group:1,size:18, title: "morning.jpeg", File_Type: "doc", label: "Ransomware", Malware_Severity: "High", Detection_Method: "Manual Scan", Affected_Process: "natural", Affected_System: "blood", User_Permissions: "Admin", Last_Modified_By: "Marcus Perez" },
{ id: 44,group:1,size:18, title: "drop.mp3", File_Type: "zip", label: "Worm", Malware_Severity: "Medium", Detection_Method: "Manual Scan", Affected_Process: "gun", Affected_System: "nor", User_Permissions: "User", Last_Modified_By: "Michael Wright" },
{ id: 45,group:1,size:18, title: "care.mp3", File_Type: "exe", label: "Worm", Malware_Severity: "Low", Detection_Method: "Manual Scan", Affected_Process: "debate", Affected_System: "us", User_Permissions: "User", Last_Modified_By: "Dr. Brandon Peterson" },
{ id: 46,group:1,size:18, title: "central.pdf", File_Type: "doc", label: "Virus", Malware_Severity: "High", Detection_Method: "Manual Scan", Affected_Process: "per", Affected_System: "form", User_Permissions: "User", Last_Modified_By: "Kyle Roberts" },
{ id: 47,group:1,size:18, title: "animal.png", File_Type: "pdf", label: "Worm", Malware_Severity: "High", Detection_Method: "Manual Scan", Affected_Process: "add", Affected_System: "not", User_Permissions: "User", Last_Modified_By: "Shawn Williams" },
{ id: 48,group:2, size:16,title: "character.webm", File_Type: "doc", label: "Trojan", Malware_Severity: "Low", Detection_Method: "Antivirus", Affected_Process: "dog", Affected_System: "response", User_Permissions: "User", Last_Modified_By: "Bonnie Clark" },
{ id: 49,group:2, size:16,title: "apply.txt", File_Type: "doc", label: "Virus", Malware_Severity: "Medium", Detection_Method: "Antivirus", Affected_Process: "since", Affected_System: "image", User_Permissions: "Admin", Last_Modified_By: "Michael Jarvis" },
{ id: 50,group:1,size:18, title: "financial.ods", File_Type: "pdf", label: "Virus", Malware_Severity: "Low", Detection_Method: "Manual Scan", Affected_Process: "ahead", Affected_System: "watch", User_Permissions: "Admin", Last_Modified_By: "Denise Bishop" },
{ id: 51,group:3,size:12,title: "television.css", File_Type: "pdf", label: "Worm", Malware_Severity: "High", Detection_Method: "Firewall Detection", Affected_Process: "beat", Affected_System: "argue", User_Permissions: "Admin", Last_Modified_By: "Catherine Ortega" },
{ id: 52,group:2, size:16,title: "research.odt", File_Type: "pdf", label: "Trojan", Malware_Severity: "Medium", Detection_Method: "Antivirus", Affected_Process: "anyone", Affected_System: "yourself", User_Permissions: "Admin", Last_Modified_By: "Teresa Taylor" },
{ id: 53,group:2, size:16,title: "speak.mp4", File_Type: "pdf", label: "Ransomware", Malware_Severity: "Low", Detection_Method: "Antivirus", Affected_Process: "mother", Affected_System: "Democrat", User_Permissions: "User", Last_Modified_By: "Kim Allen" },
{ id: 54,group:1,size:18, title: "bad.js", File_Type: "doc", label: "Ransomware", Malware_Severity: "Medium", Detection_Method: "Manual Scan", Affected_Process: "turn", Affected_System: "mouth", User_Permissions: "User", Last_Modified_By: "Tyler Daniels" },
{ id: 55,group:2, size:16,title: "rise.wav", File_Type: "pdf", label: "Virus", Malware_Severity: "Medium", Detection_Method: "Antivirus", Affected_Process: "ago", Affected_System: "clear", User_Permissions: "Admin", Last_Modified_By: "Jessica Grimes" },
{ id: 56,group:1,size:18, title: "growth.json", File_Type: "doc", label: "Trojan", Malware_Severity: "Low", Detection_Method: "Manual Scan", Affected_Process: "enjoy", Affected_System: "Mrs", User_Permissions: "User", Last_Modified_By: "Natasha Bolton" },
{ id: 57,group:3,size:12,title: "put.odp", File_Type: "zip", label: "Virus", Malware_Severity: "Low", Detection_Method: "Firewall Detection", Affected_Process: "data", Affected_System: "agency", User_Permissions: "User", Last_Modified_By: "Adam Chen" },
{ id: 58,group:3,size:12,title: "pick.doc", File_Type: "doc", label: "Trojan", Malware_Severity: "Low", Detection_Method: "Firewall Detection", Affected_Process: "own", Affected_System: "affect", User_Permissions: "Admin", Last_Modified_By: "Rebecca Garcia" },
{ id: 59,group:3,size:12,title: "rather.flac", File_Type: "pdf", label: "Trojan", Malware_Severity: "Low", Detection_Method: "Firewall Detection", Affected_Process: "set", Affected_System: "fast", User_Permissions: "User", Last_Modified_By: "Ryan Allen" },
{ id: 60,group:1,size:18, title: "method.mov", File_Type: "zip", label: "Trojan", Malware_Severity: "Medium", Detection_Method: "Manual Scan", Affected_Process: "always", Affected_System: "full", User_Permissions: "User", Last_Modified_By: "Shawn Smith" },
{ id: 61,group:1,size:18, title: "second.ods", File_Type: "doc", label: "Ransomware", Malware_Severity: "Medium", Detection_Method: "Manual Scan", Affected_Process: "avoid", Affected_System: "general", User_Permissions: "User", Last_Modified_By: "Tiffany Wells" },
{ id: 62,group:2, size:16,title: "probably.odt", File_Type: "zip", label: "Worm", Malware_Severity: "High", Detection_Method: "Antivirus", Affected_Process: "would", Affected_System: "south", User_Permissions: "User", Last_Modified_By: "Cynthia Cobb" },
{ id: 63,group:3,size:12,title: "despite.css", File_Type: "exe", label: "Virus", Malware_Severity: "Medium", Detection_Method: "Firewall Detection", Affected_Process: "model", Affected_System: "reason", User_Permissions: "User", Last_Modified_By: "Caitlin Dominguez" },
{ id: 64,group:2, size:16,title: "paper.tiff", File_Type: "pdf", label: "Worm", Malware_Severity: "High", Detection_Method: "Antivirus", Affected_Process: "owner", Affected_System: "tree", User_Permissions: "User", Last_Modified_By: "Tony Rivera" },
{ id: 65,group:1,size:18, title: "professor.xls", File_Type: "pdf", label: "Virus", Malware_Severity: "Low", Detection_Method: "Manual Scan", Affected_Process: "market", Affected_System: "ago", User_Permissions: "User", Last_Modified_By: "Lee Green" },
{ id: 66,group:1,size:18, title: "note.png", File_Type: "zip", label: "Virus", Malware_Severity: "High", Detection_Method: "Manual Scan", Affected_Process: "culture", Affected_System: "eye", User_Permissions: "User", Last_Modified_By: "Angel Marks" },
{ id: 67,group:1,size:18, title: "year.bmp", File_Type: "exe", label: "Worm", Malware_Severity: "High", Detection_Method: "Manual Scan", Affected_Process: "leader", Affected_System: "behind", User_Permissions: "User", Last_Modified_By: "Jamie Barajas" },
{ id: 68,group:2, size:16,title: "among.png", File_Type: "zip", label: "Ransomware", Malware_Severity: "High", Detection_Method: "Antivirus", Affected_Process: "pull", Affected_System: "relate", User_Permissions: "User", Last_Modified_By: "Dr. Michael Ashley" },
{ id: 69,group:3,size:12,title: "enjoy.webm", File_Type: "zip", label: "Virus", Malware_Severity: "High", Detection_Method: "Firewall Detection", Affected_Process: "result", Affected_System: "expert", User_Permissions: "Admin", Last_Modified_By: "Erin Martinez" },
{ id: 70,group:1,size:18, title: "woman.wav", File_Type: "pdf", label: "Ransomware", Malware_Severity: "Low", Detection_Method: "Manual Scan", Affected_Process: "decision", Affected_System: "shoulder", User_Permissions: "Admin", Last_Modified_By: "Melissa Woods" },
{ id: 71,group:2, size:16,title: "quickly.doc", File_Type: "doc", label: "Worm", Malware_Severity: "Medium", Detection_Method: "Antivirus", Affected_Process: "along", Affected_System: "treatment", User_Permissions: "Admin", Last_Modified_By: "Kathryn Smith" },
{ id: 72,group:1,size:18, title: "better.webm", File_Type: "doc", label: "Virus", Malware_Severity: "Low", Detection_Method: "Manual Scan", Affected_Process: "second", Affected_System: "all", User_Permissions: "User", Last_Modified_By: "Derrick Sullivan" },
{ id: 73,group:2, size:16,title: "find.wav", File_Type: "pdf", label: "Trojan", Malware_Severity: "High", Detection_Method: "Antivirus", Affected_Process: "bag", Affected_System: "key", User_Permissions: "Admin", Last_Modified_By: "Thomas Perez" },
{ id: 74,group:1,size:18, title: "want.gif", File_Type: "zip", label: "Worm", Malware_Severity: "Medium", Detection_Method: "Manual Scan", Affected_Process: "join", Affected_System: "reach", User_Permissions: "Admin", Last_Modified_By: "Kelly Garrett" },
{ id: 75,group:3,size:12,title: "support.ods", File_Type: "doc", label: "Trojan", Malware_Severity: "Low", Detection_Method: "Firewall Detection", Affected_Process: "authority", Affected_System: "participant", User_Permissions: "Admin", Last_Modified_By: "Paige Salazar" },
{ id: 76,group:1,size:18, title: "argue.flac", File_Type: "exe", label: "Ransomware", Malware_Severity: "Low", Detection_Method: "Manual Scan", Affected_Process: "American", Affected_System: "always", User_Permissions: "Admin", Last_Modified_By: "Ricky Dixon" },
{ id: 77,group:2, size:16,title: "hear.wav", File_Type: "pdf", label: "Worm", Malware_Severity: "Medium", Detection_Method: "Antivirus", Affected_Process: "structure", Affected_System: "seek", User_Permissions: "Admin", Last_Modified_By: "Joseph Dean" },
{ id: 78,group:2, size:16,title: "could.ods", File_Type: "doc", label: "Worm", Malware_Severity: "Low", Detection_Method: "Antivirus", Affected_Process: "person", Affected_System: "water", User_Permissions: "Admin", Last_Modified_By: "Margaret Irwin" },
{ id: 79,group:2, size:16,title: "agree.mp3", File_Type: "pdf", label: "Trojan", Malware_Severity: "Medium", Detection_Method: "Antivirus", Affected_Process: "over", Affected_System: "media", User_Permissions: "Admin", Last_Modified_By: "Joseph Browning" },
{ id: 80,group:1,size:18, title: "should.flac", File_Type: "pdf", label: "Ransomware", Malware_Severity: "High", Detection_Method: "Manual Scan", Affected_Process: "animal", Affected_System: "offer", User_Permissions: "Admin", Last_Modified_By: "Jennifer Keith" },
{ id: 81,group:2, size:16,title: "above.avi", File_Type: "pdf", label: "Virus", Malware_Severity: "High", Detection_Method: "Antivirus", Affected_Process: "support", Affected_System: "throw", User_Permissions: "User", Last_Modified_By: "Melissa Russell" },
{ id: 82,group:1,size:18, title: "bit.tiff", File_Type: "exe", label: "Trojan", Malware_Severity: "Low", Detection_Method: "Manual Scan", Affected_Process: "glass", Affected_System: "professor", User_Permissions: "User", Last_Modified_By: "Joel Gould" },
{ id: 83,group:3,size:12,title: "successful.odt", File_Type: "exe", label: "Ransomware", Malware_Severity: "High", Detection_Method: "Firewall Detection", Affected_Process: "agent", Affected_System: "either", User_Permissions: "User", Last_Modified_By: "Tina Jensen" },
{ id: 84,group:1,size:18, title: "industry.pages", File_Type: "zip", label: "Worm", Malware_Severity: "Medium", Detection_Method: "Manual Scan", Affected_Process: "space", Affected_System: "performance", User_Permissions: "Admin", Last_Modified_By: "Craig Choi" },
{ id: 85,group:1,size:18, title: "pass.jpeg", File_Type: "zip", label: "Worm", Malware_Severity: "Low", Detection_Method: "Manual Scan", Affected_Process: "role", Affected_System: "to", User_Permissions: "User", Last_Modified_By: "John Hurley" },
{ id: 86,group:1,size:18, title: "manager.mp3", File_Type: "exe", label: "Virus", Malware_Severity: "High", Detection_Method: "Manual Scan", Affected_Process: "remember", Affected_System: "feel", User_Permissions: "Admin", Last_Modified_By: "Jeffrey Chavez" },
{ id: 87,group:1,size:18, title: "test.flac", File_Type: "zip", label: "Trojan", Malware_Severity: "Medium", Detection_Method: "Manual Scan", Affected_Process: "kid", Affected_System: "situation", User_Permissions: "Admin", Last_Modified_By: "Melissa Bradford" },
{ id: 88,group:2, size:16,title: "surface.csv", File_Type: "exe", label: "Worm", Malware_Severity: "High", Detection_Method: "Antivirus", Affected_Process: "back", Affected_System: "simple", User_Permissions: "User", Last_Modified_By: "Nathan Schultz" },
{ id: 89,group:3,size:12,title: "book.mp4", File_Type: "doc", label: "Virus", Malware_Severity: "Medium", Detection_Method: "Firewall Detection", Affected_Process: "data", Affected_System: "activity", User_Permissions: "User", Last_Modified_By: "Catherine Hoffman" },
{ id: 90,group:2, size:16,title: "national.webm", File_Type: "exe", label: "Virus", Malware_Severity: "Low", Detection_Method: "Antivirus", Affected_Process: "decade", Affected_System: "another", User_Permissions: "Admin", Last_Modified_By: "Parker Peterson" },
{ id: 91,group:1,size:18, title: "wind.mp4", File_Type: "zip", label: "Ransomware", Malware_Severity: "High", Detection_Method: "Manual Scan", Affected_Process: "writer", Affected_System: "treat", User_Permissions: "Admin", Last_Modified_By: "Kenneth Adkins" },
{ id: 92,group:3,size:12,title: "tree.mp3", File_Type: "doc", label: "Trojan", Malware_Severity: "Medium", Detection_Method: "Firewall Detection", Affected_Process: "let", Affected_System: "around", User_Permissions: "User", Last_Modified_By: "James Frey" },
{ id: 93,group:2, size:16,title: "finish.flac", File_Type: "pdf", label: "Trojan", Malware_Severity: "Medium", Detection_Method: "Antivirus", Affected_Process: "help", Affected_System: "serve", User_Permissions: "User", Last_Modified_By: "Caleb David" },
{ id: 94,group:2, size:16,title: "myself.tiff", File_Type: "doc", label: "Ransomware", Malware_Severity: "Low", Detection_Method: "Antivirus", Affected_Process: "control", Affected_System: "yeah", User_Permissions: "User", Last_Modified_By: "David Byrd" },
{ id: 95,group:2, size:16,title: "computer.jpg", File_Type: "zip", label: "Trojan", Malware_Severity: "Low", Detection_Method: "Antivirus", Affected_Process: "ten", Affected_System: "left", User_Permissions: "Admin", Last_Modified_By: "Jason Adams" },
{ id: 96,group:1,size:18, title: "Mr.wav", File_Type: "zip", label: "Trojan", Malware_Severity: "Low", Detection_Method: "Manual Scan", Affected_Process: "with", Affected_System: "reveal", User_Permissions: "Admin", Last_Modified_By: "Ray Jackson" },
{ id: 97,group:1,size:18, title: "so.avi", File_Type: "exe", label: "Trojan", Malware_Severity: "Low", Detection_Method: "Manual Scan", Affected_Process: "once", Affected_System: "itself", User_Permissions: "User", Last_Modified_By: "Michael Parks" },
{ id: 98,group:1,size:18, title: "star.txt", File_Type: "exe", label: "Ransomware", Malware_Severity: "Low", Detection_Method: "Manual Scan", Affected_Process: "experience", Affected_System: "top", User_Permissions: "Admin", Last_Modified_By: "John Castillo" },
{ id: 99,group:3,size:12,title: "turn.csv", File_Type: "exe", label: "Trojan", Malware_Severity: "High", Detection_Method: "Firewall Detection", Affected_Process: "develop", Affected_System: "finish", User_Permissions: "User", Last_Modified_By: "Melissa Vazquez" },
{ id: 100,group:1,size:18, title: "with.ods", File_Type: "pdf", label: "Virus", Malware_Severity: "High", Detection_Method: "Manual Scan", Affected_Process: "group", Affected_System: "practice", User_Permissions: "User", Last_Modified_By: "Heidi Cantrell DDS" },
{ id: 101,group:3,size:12,title: "wife.json", File_Type: "doc", label: "Trojan", Malware_Severity: "Medium", Detection_Method: "Firewall Detection", Affected_Process: "to", Affected_System: "gas", User_Permissions: "Admin", Last_Modified_By: "Natalie Kane" },
{ id: 102,group:2, size:16,title: "fast.jpeg", File_Type: "zip", label: "Worm", Malware_Severity: "High", Detection_Method: "Antivirus", Affected_Process: "cover", Affected_System: "main", User_Permissions: "User", Last_Modified_By: "Melissa Daniels" },
{ id: 103,group:2, size:16,title: "study.doc", File_Type: "exe", label: "Virus", Malware_Severity: "Low", Detection_Method: "Antivirus", Affected_Process: "budget", Affected_System: "it", User_Permissions: "Admin", Last_Modified_By: "Nicolas Eaton" },
{ id: 104,group:3,size:12,title: "speak.pptx", File_Type: "zip", label: "Ransomware", Malware_Severity: "Medium", Detection_Method: "Firewall Detection", Affected_Process: "speak", Affected_System: "friend", User_Permissions: "Admin", Last_Modified_By: "Sharon Cooper" },
{ id: 105,group:3,size:12,title: "her.avi", File_Type: "pdf", label: "Trojan", Malware_Severity: "High", Detection_Method: "Firewall Detection", Affected_Process: "reality", Affected_System: "address", User_Permissions: "Admin", Last_Modified_By: "Cynthia Heath" },
{ id: 106,group:3,size:12,title: "price.doc", File_Type: "exe", label: "Ransomware", Malware_Severity: "High", Detection_Method: "Firewall Detection", Affected_Process: "imagine", Affected_System: "according", User_Permissions: "Admin", Last_Modified_By: "Patrick Ewing" },

    



   
]
export var edges = [
    { from: 2, to: 7 },
{ from: 1, to: 8 },
{ from: 3, to: 9 },
{ from: 2, to: 10 },
{ from: 1, to: 11 },
{ from: 1, to: 12 },
{ from: 3, to: 13 },
{ from: 3, to: 14 },
{ from: 1, to: 15 },
{ from: 2, to: 16 },
{ from: 2, to: 17 },
{ from: 1, to: 18 },
{ from: 1, to: 19 },
{ from: 1, to: 20 },
{ from: 3, to: 21 },
{ from: 1, to: 22 },
{ from: 3, to: 23 },
{ from: 2, to: 24 },
{ from: 2, to: 25 },
{ from: 3, to: 26 },
{ from: 3, to: 27 },
{ from: 3, to: 28 },
{ from: 3, to: 29 },
{ from: 2, to: 30 },
{ from: 1, to: 31 },
{ from: 3, to: 32 },
{ from: 2, to: 33 },
{ from: 3, to: 34 },
{ from: 3, to: 35 },
{ from: 2, to: 36 },
{ from: 2, to: 37 },
{ from: 1, to: 38 },
{ from: 2, to: 39 },
{ from: 3, to: 40 },
{ from: 3, to: 41 },
{ from: 3, to: 42 },
{ from: 1, to: 43 },
{ from: 1, to: 44 },
{ from: 1, to: 45 },
{ from: 1, to: 46 },
{ from: 1, to: 47 },
{ from: 2, to: 48 },
{ from: 2, to: 49 },
{ from: 1, to: 50 },
{ from: 3, to: 51 },
{ from: 2, to: 52 },
{ from: 2, to: 53 },
{ from: 1, to: 54 },
{ from: 2, to: 55 },
{ from: 1, to: 56 },
{ from: 3, to: 57 },
{ from: 3, to: 58 },
{ from: 3, to: 59 },
{ from: 1, to: 60 },
{ from: 1, to: 61 },
{ from: 2, to: 62 },
{ from: 3, to: 63 },
{ from: 2, to: 64 },
{ from: 1, to: 65 },
{ from: 1, to: 66 },
{ from: 1, to: 67 },
{ from: 2, to: 68 },
{ from: 3, to: 69 },
{ from: 1, to: 70 },
{ from: 2, to: 71 },
{ from: 1, to: 72 },
{ from: 2, to: 73 },
{ from: 1, to: 74 },
{ from: 3, to: 75 },
{ from: 1, to: 76 },
{ from: 2, to: 77 },
{ from: 2, to: 78 },
{ from: 2, to: 79 },
{ from: 1, to: 80 },
{ from: 2, to: 81 },
{ from: 1, to: 82 },
{ from: 3, to: 83 },
{ from: 1, to: 84 },
{ from: 1, to: 85 },
{ from: 1, to: 86 },
{ from: 1, to: 87 },
{ from: 2, to: 88 },
{ from: 3, to: 89 },
{ from: 2, to: 90 },
{ from: 1, to: 91 },
{ from: 3, to: 92 },
{ from: 2, to: 93 },
{ from: 2, to: 94 },
{ from: 2, to: 95 },
{ from: 1, to: 96 },
{ from: 1, to: 97 },
{ from: 1, to: 98 },
{ from: 3, to: 99 },
{ from: 1, to: 100 },
{ from: 3, to: 101 },
{ from: 2, to: 102 },
{ from: 2, to: 103 },
{ from: 3, to: 104 },
{ from: 3, to: 105 },
{ from: 3, to: 106 },
{ from: 4, to: 7 },
{ from: 6, to: 8 },
{ from: 6, to: 9 },
{ from: 6, to: 10 },
{ from: 5, to: 11 },
{ from: 5, to: 12 },
{ from: 4, to: 13 },
{ from: 6, to: 14 },
{ from: 5, to: 15 },
{ from: 4, to: 16 },
{ from: 6, to: 17 },
{ from: 5, to: 18 },
{ from: 4, to: 19 },
{ from: 5, to: 20 },
{ from: 6, to: 21 },
{ from: 6, to: 22 },
{ from: 6, to: 23 },
{ from: 4, to: 24 },
{ from: 6, to: 25 },
{ from: 5, to: 26 },
{ from: 4, to: 27 },
{ from: 6, to: 28 },
{ from: 6, to: 29 },
{ from: 6, to: 30 },
{ from: 4, to: 31 },
{ from: 6, to: 32 },
{ from: 4, to: 33 },
{ from: 5, to: 34 },
{ from: 4, to: 35 },
{ from: 5, to: 36 },
{ from: 6, to: 37 },
{ from: 4, to: 38 },
{ from: 5, to: 39 },
{ from: 5, to: 40 },
{ from: 4, to: 41 },
{ from: 6, to: 42 },
{ from: 6, to: 43 },
{ from: 5, to: 44 },
{ from: 4, to: 45 },
{ from: 6, to: 46 },
{ from: 6, to: 47 },
{ from: 4, to: 48 },
{ from: 5, to: 49 },
{ from: 4, to: 50 },
{ from: 6, to: 51 },
{ from: 5, to: 52 },
{ from: 4, to: 53 },
{ from: 5, to: 54 },
{ from: 5, to: 55 },
{ from: 4, to: 56 },
{ from: 4, to: 57 },
{ from: 4, to: 58 },
{ from: 4, to: 59 },
{ from: 5, to: 60 },
{ from: 5, to: 61 },
{ from: 6, to: 62 },
{ from: 5, to: 63 },
{ from: 6, to: 64 },
{ from: 4, to: 65 },
{ from: 6, to: 66 },
{ from: 6, to: 67 },
{ from: 6, to: 68 },
{ from: 6, to: 69 },
{ from: 4, to: 70 },
{ from: 5, to: 71 },
{ from: 4, to: 72 },
{ from: 6, to: 73 },
{ from: 5, to: 74 },
{ from: 4, to: 75 },
{ from: 4, to: 76 },
{ from: 5, to: 77 },
{ from: 4, to: 78 },
{ from: 5, to: 79 },
{ from: 6, to: 80 },
{ from: 6, to: 81 },
{ from: 4, to: 82 },
{ from: 6, to: 83 },
{ from: 5, to: 84 },
{ from: 4, to: 85 },
{ from: 6, to: 86 },
{ from: 5, to: 87 },
{ from: 6, to: 88 },
{ from: 5, to: 89 },
{ from: 4, to: 90 },
{ from: 6, to: 91 },
{ from: 5, to: 92 },
{ from: 5, to: 93 },
{ from: 4, to: 94 },
{ from: 4, to: 95 },
{ from: 4, to: 96 },
{ from: 4, to: 97 },
{ from: 4, to: 98 },
{ from: 6, to: 99 },
{ from: 6, to: 100 },
{ from: 5, to: 101 },
{ from: 6, to: 102 },
{ from: 4, to: 103 },
{ from: 5, to: 104 },
{ from: 6, to: 105 },
{ from: 6, to: 106 },


]